name: Quotes
favicon: null
layout_spectrum: 0.6161922523751855
typography_spectrum: 0.48203724389895797
title: The Quotes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.21730130189098418
  lightness: 0.8648851381149143
  saturation: 0.0753749618306756
  rhythmicContrast: 0.3521656913217157
purpose: []
